import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import React from "react";

const layout = ({ children, isHomePage, to = "/" }) => {
  return (
    <>
      <Head>
        <title>Next app</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <header className="bg-body-tertiary">
        <nav className="navbar  px-5 py-2">
          <Link href="/">LOGO</Link>
          <div className="d-flex align-items-center">
            <Link href="/blog">Blog</Link>
            <form
              className="d-flex ms-4"
              role="search"
            >
              <input
                className="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button
                className="btn btn-outline-success"
                type="submit"
              >
                Search
              </button>
            </form>
          </div>
        </nav>
      </header>
      {!isHomePage && (
        <Link
          href={to}
          className="btn btn-primary mt-3 ms-3"
        >
          Back to {to === "/" ? "home" : "blog"}
        </Link>
      )}
      <main>{children}</main>
    </>
  );
};

export default layout;
